<?php
/**
 * Licence 
 * 
 * This software is distributed under the terms and conditions of the GNU General Public Licence, v 3 (GPL). 
 * The complete terms and conditions of the GPL are available at http://www.gnu.org/licenses/gpl-3.0.txt
 * 
 * Copyright Notice 
 *
 * Copyright © NSW Technical and Further Education Commission (TAFE NSW), TAFE eLearning Hub 2012 
 *
 * Acknowledgements
 * - Renee Lance, project manager and lead designer 
 * - Glen Byram, lead programmer
 *
 * Sets up input screen for configuration of the theme.
 * Values are written to the _config_plugins table of the database.
 *
 * This file is just a wrapper to satisfy the Moodle API for site admin theme configuration. 
 * Because the iCan.D. theme allows configuration to be done at both SITE and COURSE level, the 
 * real input form is generated by settings_inc.php, which is shared by the standard Moodle site admin menu, and
 * a theme-specific popup for configuring course-specific overrides.
 *
 * @package		theme
 * @subpackage	icand
 * @copyright	NSW Technical and Further Education Commission (TAFE NSW), TAFE eLearning Hub 2012
 * @license     http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 * @author		Glen Byram (NSW TAFE eLearning Hub)
 * @version		04Oct2012
 * @see			settings_inc.php
 * @see			ThemeRealVisChecker_inc.php
 */


/* EXTERNAL
 * $settings : an public array declared in /lib/adminlib.php 
 *		(overwritten when settings are displayed/edited)
 * the settings objects (from /lib/adminlib.php 
 * get_string(..) will use values declared in this theme's ./lang/xx.php
 *
 * included in admin_settingpage declared in /lib/adminlib.php 
 *
 * This is called EVERY TIME _ANY_ SETTINGS PAGE IS INVOKED for admin user!!!
 *
 * table: *_config_plugins
 */
 
defined('MOODLE_INTERNAL') || die;

/*	The theme has an authorisation system to restrict who can enter theme configuration.
	The current script will be called only for site admins, so here we use a dummy authorisation object
	that allows everything. The object for COURSE level authorisation is in ThemeRealVisChecker_inc.php
 */
if (!class_exists('visibility_all')) {	// somehow this file is being loaded more than once.
	class visibility_all {
			// dummy functions here, but relevant for the popup/override version
		public function isVisible( $p_anything ) { return true; }
		public function isAnyVisible()			 { return true; }
		public function isAdminOnly($p_anything) { return false; }
		public function isUploadOK() 			 { return true; }
		public function isAlwaysForbidden($p_anything) {return  (in_array( $p_anything, 
													IcandConstantsBackend::$COURSE_OVERRIDES_NOT_ALLOWED ));}
	}
}

$vischecker = new visibility_all();
$uniqueHREFsuffix = '';
$popup_override = false;

$l_multichoiceOverrides = null;	// dummy value. In the popup, this is an array
require_once(dirname(__FILE__) . '/settings_inc.php' );